### PR TITLE
Add some standard methods to Message

### PR DESCRIPTION
**Pull request by thofmann**
This adds `fromString`, `fromJSON`, `toObject`, `toJSON`, `toString`,
and `inspect` to Message. These methods are trivial since Message only
contains a string message, but they should probably be added for
consistency.

Should toBuffer/fromBuffer be added as well?

### CODE REVIEW

**Comment by maraoz** [comment]
LGTM.
I don't know why travis is not running. Will check that

**Comment by maraoz** [comment]
travis detected 2 tests failing. can you check that?
https://travis-ci.org/bitpay/bitcore-message/builds/50084089#L227

You can run tests locally with `mocha` or better `gulp test`

**Comment by thofmann** [comment]
Sorry about that! The tests were comparing `toString` against the Message (`inspect`) instead of the original text variable. Local tests run successfully for me now.

**Comment by maraoz** [comment]
thanks again @thofmann!

**Pull request merged**
