### PR TITLE
Fix #23

### LINKED ISSUE #23: Make bitcore-lib a peer dependency
Solving all "include guard" headaches: https://github.com/bitpay/bitcore-lib/issues/21

### PR DESCRIPTION
**Pull request by levino**
See #23 for details.

### CODE REVIEW

**Comment by levino** [comment]
Is anyone maintaining this?

**Comment by levino** [comment]
Nobody is maintaining this. Closing my PR. :cry:

**Comment by martindale** [comment]
IMO, the PR should stay open so future visitors can see it in "Pull requests" and choose to merge it into their own forks.

On that note, ACK on this, and I'll be merging it into my own!

**Comment by levino** [comment]
It shows as an open PR on my personal "PR list", which is annoying because it is a kind of "to do" for me. Any idea how to make everyone happy @martindale ?

**Comment by levino** [comment]
Closing this because this is all outdated anyhow.

**Pull request closed without merging**
